POST localhost:8080/persons/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluMUBtYWlsLnJ1IiwiUm9sZSI6ImFkbWluIiwiTmFtZSI6IkFkbWluIiwiSWQiOjV9.nH_hB-f7UEdRdZ14M4tEtqghgg6zZVt-fpMP2Pp0MKg
Content-Type: application/json

{
  "id": 8,
  "name": "Федор",
  "age": 33,
  "email": "user9@mail.ru",
  "phoneNumber": "+7 933 3323333",
  "password" : "12345"
}